<?php

/**
 * Implements hook_theme().
 */
function custom_module_theme($existing, $type, $theme, $path): array
{
  $items['testModule'] = array(
    'main_template' => array(
      'variables' => array(
        'name' => '',
        'title' => '',
      ),
      'template' => 'main-template',
      'path' => drupal_get_path('module', 'drupal_module_test') . '/templates',
    ),
  );

  return $items;
}
