<?php

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
/**
 * Implements hook_ENTITY_TYPE_view_alter() for nodes.
 */
function pdfButtonModule_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display): void
{

  // Vérifiez si le type de contenu est "article".
  if ($entity->getType() === 'article' || $entity->getType() === 'article_image' ) {
    $url = Url::fromRoute('pdfButtonModule.export_pdf', ['node' => $entity->id()]);
    $url_options = [
      'attributes' => [
        'class' => [
          // Add or remove CSS classes here
          'button',
          'button--small'
        ],
      ],
    ];
    $url->setOptions($url_options);

    // Ajoutez le lien d'export PDF au rendu du nœud.
    $build['pdfButtonModule_export_pdf_link'] = [
      '#type' => 'link',
      '#title' => t('Export PDF test'),
      '#url' => $url,
    ];
  }
}
